FORMAT: 1A
HOST: http://payments-api.blim.com/

# Payments API

Payments API is a simple application allowing consumers to manipulate payment methods and transaction data.

# Group Payment Method

## Create [/payment-method]
Allows the consumer to create a payment method for a specific user.

### Create a Payment Method [POST]

+ Request (application/json)
    + Attributes (Payment Method Request)

+ Response 201 (application/json)
    + Attributes (Base Response)
        + headers (Payment Method Headers)
        + data (Payment Method Data)

## Fetch [/payment-method/{id}]
Allows the consumer to fetch a payment method for a specific user.

### Fetch a Payment Method [GET]

+ Response 200 (application/json)
    + Attributes (Base Response)
        + data (Payment Method Data)

# Group Transaction

## Create [/transaction]
Allows the consumer to create a transaction of a certain type for a specific user.

### Create a New Transaction [POST]

+ Request (application/json)
    + Attributes (Transaction Request)

+ Response 201 (application/json)
    + Attributes (Base Response)
        + data (Transaction Data)

## Fetch [/transaction/{id}]
Allows the consumer to fetch a transaction for a specific user.

### Fetch a Transaction [GET]

+ Response 200 (application/json)
    + Attributes (Base Response)
        + data (Transaction Data)

# Data Structures

## Base Response (object)
+ headers (array)
+ data (array)
+ messages (array)

## Base Request (object)
+ user_id: 1 (number, required)
+ amount: 109.00 (number, required)
+ currency_iso_code (enum[string], required)
    + Members
        + `MXN` - Mexican Peso
        + `USD` - United States Dollar
+ country_iso_code (enum[string], required)
    + Members
        + `MX` - Mexico
        + `US` - United States


## Payment Method Request (Base Request)
+ adapter (enum[string], required)
    + Members
        + `spreedly` - Spreedly Adapter
        + `braintree` - Braintree Adapter
        + `mercadopago` - Mercado Pago Adapter
+ payment_method_token: deadbeef (string, required)

## Payment Method Headers (object)
+ is_unique: true (boolean)

## Payment Method Data (object)
+ id: 1 (number, required)


## Transaction Request (Base Request)
+ type: subscription (enum[string], required)
    + Members
        + `subscription` - Subscription Transaction

## Transaction Data (object)
+ id: 1 (number, required)