FORMAT: 1A
HOST: http://payments-api.blim.com/

# Payments API

Payments API is a simple application allowing consumers to manipulate payment methods and transaction data.

# Group Payment Method

## Create [/payment-method]
Allows the consumer to create a payment method for a specific user.

### Create a Payment Method [POST]

+ Request (application/json)
    + Attributes (Payment Method Request)

+ Response 201 (application/json)
    + Attributes (Base Response)
        + headers (Payment Method Headers)
        + data (Payment Method Data)

## Read [/payment-method/{id}]
Allows the consumer to fetch a payment method for a specific user.

### Fetch a Payment Method [GET]

+ Response 200 (application/json)
    + Attributes (Base Response)
        + data (Payment Method Data)

# Group Transaction

## Create [/transaction]
Allows the consumer to create a transaction of a certain type for a specific user.

### Create a New Transaction [POST]

+ Request (application/json)
    + Attributes (Transaction Request)

+ Response 201 (application/json)
    + Attributes (Base Response)
        + data (Transaction Data)

## Read [/transaction/{id}]
Allows the consumer to fetch a transaction for a specific user.

### Fetch a Transaction [GET]

+ Response 200 (application/json)
    + Attributes (Base Response)
        + data (Transaction Data)

# Data Structures

## Base Response (object)
+ headers (array)
+ data (array)
+ messages (array)

## Base Request (object)
+ account_id: 1 (number, required) - Account ID
+ currency_code (enum[string], required) - Currency ISO Code
    + Members
        + MXN - Mexican Peso
        + USD - United States Dollar
+ country_code (enum[string], required) - Country ISO Code
    + Members
        + MX - Mexico
        + US - United States


## Payment Method Request (Base Request)
+ adapter (enum[string], required) - Gateway Adapter
    + Members
        + SPREEDLY - Spreedly Adapter
        + BRAINTREE - Braintree Adapter
        + MERCADOPAGO - Mercado Pago Adapter
+ external_token: deadbeef (string, required) - External Payment Method Token
+ verification_amount: 10 (number) - Verification Amount (Optional)

## Payment Method Headers (object)
+ is_unique: true (boolean)

## Payment Method Data (object)
+ id: 1 (number)


## Transaction Request (Base Request)
+ amount: 109 (number, required) - Transaction Amount
+ type (enum[string], required) - Transaction Type
    + Members
        + subscription - Subscription Transaction
        + verification - Verification Transaction

## Transaction Data (object)
+ id: 1 (number)